apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  labels:
  {{- include "color.labels" . | nindent 4 }}
data:
  ELASTICACHE_PASSWORD: {{ required "color.elasticachePassword is required" .Values.secret.elasticachePassword
    | b64enc | quote }}
  SECRET_KEY: {{ required "color.secretKey is required" .Values.secret.secretKey |
    b64enc | quote }}
type: Opaque
