# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DOCKER_BUILDKIT: 1

stages:
- stage: Build_and_Push
  displayName: Build and Push image
  jobs:
  - job: Build_and_Push
    displayName: Build and Push image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/color/Dockerfile'
        repository: $(DOCKER_REPOSITORY_NAME)
        tags: |
          $(tag)
    - task: ECRPushImage@1
      displayName: Push an image
      inputs:
        awsCredentials: 'aws'
        regionName: $(AWS_REGION)
        imageSource: 'imagename'
        sourceImageName: $(DOCKER_REPOSITORY_NAME)
        sourceImageTag: $(tag)
        repositoryName:  $(DOCKER_REPOSITORY_NAME)
        pushTag: $(tag)
