# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build_and Push
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/color/Dockerfile'
        repository: '704855531002.dkr.ecr.us-west-2.amazonaws.com/dallin-ecr-lab'
        # tags: |
        #   $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS ECR'
        regionName: 'us-west-2'
        imageSource: 'imagename'
        sourceImageName: '704855531002.dkr.ecr.us-west-2.amazonaws.com/dallin-ecr-lab'
        sourceImageTag: $(Build.BuildId)
        repositoryName: '704855531002.dkr.ecr.us-west-2.amazonaws.com/dallin-ecr-lab'
        pushTag: latest
        logRequest: true
        logResponse: true

